#ifndef __CosExternalizationReference_idl__
#define __CosExternalizationReference_idl__

#include <coss/CosExternalization.idl>
#include <coss/CosReference.idl>

#pragma prefix "omg.org"


module CosExternalizationReference {
  
  interface Relationship :
      ::CosCompoundExternalization::Relationship,
      ::CosReference::Relationship {};

  interface ReferencesRole :
      ::CosCompoundExternalization::Role,
      ::CosReference::ReferencesRole {};

  interface ReferencedByRole :
      ::CosCompoundExternalization::Role,
      ::CosReference::ReferencedByRole {};
 
};


#endif

