// **********************************************************************
// CosLifeCycleContainment
// **********************************************************************

#include <coss/CosCompoundLifeCycle.idl>
#include <coss/CosContainment.idl>

#ifndef __CosLifeCycleContainment_idl__
#define __CosLifeCycleContainment_idl__

#pragma prefix "omg.org"

module CosLifeCycleContainment {
  
  interface Relationship :
      ::CosContainment::Relationship,
      ::CosCompoundLifeCycle::Relationship {};

  interface ContainsRole :
      ::CosContainment::ContainsRole,
      ::CosCompoundLifeCycle::Role {};

  interface ContainedInRole :
      ::CosContainment::ContainedInRole,
      ::CosCompoundLifeCycle::Role {};
 
};

#endif

