// **********************************************************************
// CosLifeCycleReference
// **********************************************************************

#include <coss/CosCompoundLifeCycle.idl>
#include <coss/CosReference.idl>

#ifndef __CosLifeCycleReference_idl__
#define __CosLifeCycleReference_idl__

#pragma prefix "omg.org"


module CosLifeCycleReference {
  
  interface Relationship :
      ::CosReference::Relationship,
      ::CosCompoundLifeCycle::Relationship {};

  interface ReferencesRole :
      ::CosReference::ReferencesRole,
      ::CosCompoundLifeCycle::Role {};

  interface ReferencedByRole :
      ::CosReference::ReferencedByRole,
      ::CosCompoundLifeCycle::Role {};
 
};


#endif

