#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $targetType specie
wmake $targetType solidSpecie
wmake $targetType thermophysicalFunctions
./properties/Allwmake $*

wmake $targetType basic
wmake $targetType reactionThermo
wmake $targetType laminarFlameSpeed
wmake $targetType chemistryModel
wmake $targetType barotropicCompressibilityModel
wmake $targetType SLGThermo


wmake $targetType solidThermo
wmake $targetType solidChemistryModel

wmake $targetType radiationModels

# ----------------------------------------------------------------- end-of-file
