#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean regionModel
wclean pyrolysisModels
wclean surfaceFilmModels
wclean thermalBaffleModels
wclean regionCoupling


# ----------------------------------------------------------------- end-of-file
