#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake
wmake interDyMFoam
wmake LTSInterFoam
wmake interMixingFoam

# ----------------------------------------------------------------- end-of-file
