#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments
genDoc=0
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

wmakeCheckPwd "$WM_PROJECT_DIR" || {
    echo "Error: Current directory is not \$WM_PROJECT_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

# wmake is required for subsequent targets
(cd wmake/src && make)

# Build ThirdParty sources
if [ -d "$WM_THIRD_PARTY_DIR" ]
then
    $WM_THIRD_PARTY_DIR/Allwmake
else
    echo "no ThirdParty sources found - skipping"
fi

# Build OpenFOAM libraries and applications
src/Allwmake $targetType $*

# Build OpenFOAM libraries and applications
applications/Allwmake $targetType $*

# Optionally build OpenFOAM Doxygen documentation
[ $genDoc -eq 1 ] && doc/Allwmake

# ----------------------------------------------------------------- end-of-file
