#                            -*- mode: org; -*-
#
#+TITLE:                README for OpenFOAM-history
#+AUTHOR:                      OpenCFD Ltd.
#+DATE:                      19th March 2015
#+LINK:                  http://www.openfoam.org
#+OPTIONS: author:nil ^:{} toc:nil
Copyright (c) 2015 OpenFOAM Foundation.

Copyright (c) 2015 OpenCFD Ltd. (See Changes)

* Announcement
  ESI/OpenCFD is pleased to announce the transfer of code and copyright to
  the OpenFOAM Foundation of all developments since the last major release
  (version 2.3).

* About this version
  The OpenFOAM-history repository is a frozen version, and not under active
  development.  It is not the official version of OpenFOAM (see
  [[http://www.OpenFOAM.org][OpenFOAM Foundation]] for information relating to
  official releases).
  It consolidates a history of contributions by
  [[http://www.OpenFOAM.com][OpenCFD]], sponsors and partners,
  committed to releasing code openly under the terms of the GPL.

* About OpenFOAM
  OpenFOAM is a free, open source computational fluid dynamics (CFD) software
  package released by the OpenFOAM Foundation. It has a large user base across
  most areas of engineering and science, from both commercial and academic
  organisations. OpenFOAM has an extensive range of features to solve anything
  from complex fluid flows involving chemical reactions, turbulence and heat
  transfer, to solid dynamics and electromagnetics.

* Copyright
  OpenFOAM is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  See the file =COPYING= in this directory or
  [[http://www.gnu.org/licenses/]], for a description of the GNU General Public
  License terms under which you can copy the files.

* [[http://www.OpenFOAM.org/git.php][Download and installation instructions]]
* [[http://www.OpenFOAM.org/docs][Documentation]]
* [[http://OpenFOAM.github.io/Documentation-dev/html][Source code documentation]]
* [[http://www.OpenFOAM.org/bugs][Reporting bugs in OpenFOAM]]
* [[http://www.openfoam.org/contact][Contacting the OpenFOAM Foundation]]

OpenFOAM is a registered trademark of ESI/OpenCFD.

* Changes
  - OpenCFD 19/03/2015: Title: Updated version to OpenFOAM-history
  - OpenCFD 19/03/2015: Author: OpenFOAM Foundation to OpenCFD Ltd.
  - OpenCFD 19/03/2015: Date: date of changes
  - OpenCFD 19/03/2015: Added 'Announcement' paragraph
  - OpenCFD 19/03/2015: Added 'About this version' paragraph
  - OpenCFD 19/03/2015: Added trademark information
