#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.pre

# Set application name
application=$(getApplication)

# Get number of processors to run on
nProcs=4 #$(getNumberOfProcessors)

# decompose
runApplication -l log.decomposePar.cabin decomposePar -region cabin
runApplication -l log.decomposePar.ice decomposePar -region ice
runApplication -l log.decomposePar.exterior decomposePar -region exterior

runParallel $application $nProcs

runApplication -l log.reconstructPar.cabin reconstructPar -region cabin
runApplication -l log.reconstructPar.ice reconstructPar -region ice
runApplication -l log.reconstructPar.exterior reconstructPar -region exterior
