#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication decomposePar -cellDist

# Write geometry
runParallel createExternalCoupledPatchGeometry 4 coupleGroup

# Start application in background
runParallel $(getApplication) 4 &

./externalSolver

runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
