#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2011-2014 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     addCompile
#
# Description
#     Cleans up the dependency list and add the compilation statement.
#
#     Usage: wmkdep <fileName> | addCompile <source fileName> <dep fileName>
#
#------------------------------------------------------------------------------

# Source file name manipulation
sourceName=${1##*/}
sourceDir=${1%/*}
objectName=${1%.*}.o
sub=${1##*.}

if [ "$sourceDir" = "$sourceName" ]
then
    sourceDir=.
fi

# Dependency file name
depName=$2

# Make the directory for the dependency and object files
objectDir=${2%/*}
mkdir -p $objectDir

# Replace the 'WM_PROJECT_DIR' path with the '$(WM_PROJECT_DIR)' variable
if [ "$WM_PROJECT_DIR" ]
then
    sed -e s%$WM_PROJECT_DIR%'$(WM_PROJECT_DIR)'% > $depName
else
    cat > $depName
fi

# Add the '$(OBJECTS_DIR)' path component to the object file
sed -e s%".*.o.*:"%'$(OBJECTS_DIR)/'"$objectName\:"%  \
    -e s%$WM_PROJECT_DIR%'$(WM_PROJECT_DIR)'%         \
    >> $depName

# Complete the dependencies
echo '$(OBJECTS_DIR)/'$objectName': $(EXE_DEP)' >> $depName
echo '$(OBJECTS_DIR)/'$objectName':' >> $depName

# Add the definition of the 'SOURCE_DIR' variable
echo '	@SOURCE_DIR='$sourceDir >> $depName

# Add the compilation statement
echo '	SOURCE='$1' ; $('$sub'too)' >> $depName


#------------------------------------------------------------------------------
