.TH CONSTANTS 5 "July, 2007" "LAM 7.1.4" "LAM FORTRAN LIBRARY"
.SH NAME
CONSTANTS \- constants for LAM Fortran programming
.SH DESCRIPTION
The following table describes the values appropriate to various constants
used in LAM.
It also describes the meaning of the constants and 
lists the cpp(1) header files in which the constants can be found.
To use these files, the Fortran source files will need to be
passed through cpp(1) before they are given to the Fortran compiler.
Some compiler drivers will run cpp(1) if the source file suffix is .F.
.PP
In lieu of cpp(1), the constants can be copied to parameter statements
in the Fortran source files.
.PP
.nf
.if n .ta 12 25 29 64
.if t .ta 12 25 29 64
CONSTANT	VALUE	DESCRIPTION	FILE

.B "Network Constants:"

LOCAL	-2147483647	local node		NET.h
MAXNMSGLEN	8192	maximum length of one message packet		NET.h
NHDSIZE	8	maximum size in words of \fIndata\fR		NET.h
			argument	
NOTNODEID	-2147483648	error occurred in IGNDID(2)		NET.h
NOTNODETYPE	-2147483648	error occurred in IGRTP(2)	NET.h

.B "Node Types:"

NTCAST	2	multicast definition	NET.h
NTWASTE	4	not fully used/wasted	NET.h
NTDISK	8	node with attached disk	NET.h
NTTUBE	16	node with attached video unit	NET.h
NTJONES	32	node is a neighbour	NET.h
NTBOOT	64	neighbour node to boot	NET.h
NTALL	127	matches any type	NET.h

.B "Message Flags:"

NOBUF	16	turn off buffering	NET.h
NREEL	1024	multireel	NET.h
DRAWDATA	65536	\fIndata\fR representation will not be	NET.h
			changed	
DINT4DATA	131072	\fIndata\fR holds 8 32-bit integer	NET.h
DFLT4DATA	262144	\fIndata\fR holds 8 single precision reals	NET.h
DFLT8DATA	524288	\fIndata\fR holds 4 double precision reals	NET.h
DRAWMSG	1048576	\fInmsg\fR representation will not be	NET.h
			changed	
DINT4MSG	2097152	\fInmsg\fR holds integers	NET.h
DFLT4MSG	4194304	\fInmsg\fR holds single precision reals	NET.h
DFLT8MSG	8388608	\fInmsg\fR holds double precision reals	NET.h

.B "Reserved Cast Identifiers:"

HOST2ALL	-2147483646	multicast from origin to all nodes	NET.h
HOST2COMP	-2147483642	multicast from origin to compute nodes	NET.h

.B "File Flags:"

O_RDONLY	0	open for reading only	FREQ.h
O_WRONLY	1	open for writing only	FREQ.h
O_RDWR	2	open for reading and writing	FREQ.h
O_APPEND	8	append on each write	FREQ.h
O_CREAT	512	create file if it does not exist	FREQ.h
O_TRUNC	1024	truncate length to 0	FREQ.h
O_EXCL	2048	error if create and file exists	FREQ.h
O_SYNC	8192	update file data and file status	FREQ.h
		before writing
O_LOCK	65536	lock file descriptor active	FREQ.h
O_REUSE	131072	reuse existing file descriptor	FREQ.h
O_1WAY	4194304	do not acknowledge writes	FREQ.h

.B "Process Runtime Flags:"

RTF_WAIT	16	child sends a message to	NET.h
			parent when it exits
RTF_TRACE	256	enable process tracing	NET.h
