#!/bin/sh

MICORC=/dev/null
export MICORC

# run Server
rm -f hello.ref
./server &
server_pid=$!
renice 19 $server_pid >/dev/null

trap "kill $server_pid > /dev/null 2> /dev/null" 0
for i in 0 1 2 3 4 5 6 7 8 9 ; do if test -r hello.ref ; then break ; else sleep 1 ; fi ; done

# run client
./client
sleep 2
