.TH MPI_Win_Test 3 "6/24/2006" "LAM/MPI 7.1.4" "LAM/MPI"
.SH NAME
MPI_Win_Test \-  Test for progress on a window 
.SH SYNOPSIS
.nf
#include <mpi.h>
int MPI_Win_test(MPI_Win win, int *flag)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B win 
- window (handle)
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B flag 
- (integer)
.PD 1

.SH NOTES

This function is currently not implemented in LAM/MPI.  It will return
an MPI_ERR_OTHER run time error.

.SH NOTES FOR FORTRAN

All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
)
have an additional argument 
.I ierr
at the end of the argument list.
.I ierr
is an integer and has the same meaning as the return value of
the routine in C.  In Fortran, MPI routines are subroutines, and are
invoked with the 
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type
.I INTEGER
in Fortran.
.SH LOCATION
wtest.c
