#!/bin/sh

MICORC=/dev/null
export MICORC

# run Server
rm -f bar.ref
./server &
server_pid=$!

trap "kill $server_pid > /dev/null 2> /dev/null" 0
for i in 0 1 2 3 4 5 6 7 8 9 ; do if test -r bar.ref ; then break ; else sleep 1 ; fi ; done

# run client
echo -n "Test variable-length _out param (object reference)..."
./client

