// -*- c++ -*-

#ifndef __CURRENT_IDL__
#define __CURRENT_IDL__

#pragma prefix "omg.org"

module CORBA {

  interface Current {
  };

  interface PrincipalCurrent : Current {
    CORBA::Principal get_principal ();
  };
};

#endif // __CURRENT_IDL__
