// Time  Service v1.0 described in CORBAservices: Common Object Services
// Specification, chapter 14 

#ifndef TimeBase_IDL
#define TimeBase_IDL

#pragma prefix "omg.org"

module TimeBase {

  typedef unsigned long long TimeT;

  typedef TimeBase::TimeT InaccuracyT;

  typedef short TdfT;

  struct UtcT {
    TimeBase::TimeT time;
    unsigned long inacclo;
    unsigned short inacchi;
    TimeBase::TdfT tdf;
  };

  struct IntervalT {
    TimeBase::TimeT lower_bound;
    TimeBase::TimeT upper_bound;
  };

};
#endif
