#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $targetType potential
wmake $targetType molecularMeasurements
wmake $targetType molecule

# ----------------------------------------------------------------- end-of-file
