#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

decompose/Allwmake $targetType $*
reconstruct/Allwmake $targetType $*
wmake $targetType distributed


# ----------------------------------------------------------------- end-of-file
