.\"
.\" MICO --- a CORBA 2.0 implementation
.\" Copyright (C) 1997 Kay Roemer & Arno Puder
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" Send comments and/or bug reports to:
.\"                mico@informatik.uni-frankfurt.de
.\"
.TH NSD 8 "April 8 1997"
.SH NAME
nsd \- MICO name service server
.SH SYNOPSIS
.BR nsd
.br
.SH DESCRIPTION
.BR nsd
implements the COS compliant naming service. To use it you have
to run
.BR micod ,
create an entry for the naming service in the implementation repository
using the
.BR imr
tool and pass the clients the address of the naming service using the
.BR -ORBNamingAddr
option.
.SH OPTIONS
Only standard ORB options.
.SH FILES
~/.micorc
.SH "SEE ALSO"
.IR "MICO Reference Manual" ", " rsh(1) ", " micod(8) ", " imr(1) ", "
.IR micorc(5) ", " idl(1) ", " nsadmin(1)
.SH COPYRIGHT
Copyright (C) 1997, Kai-Uwe Sattler
.SH AUTHOR
Kai-Uwe Sattler
