#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $targetType distributionModels
wmake $targetType basic
wmake $targetType solidParticle
wmake $targetType intermediate
wmake $targetType turbulence
wmake $targetType spray
wmake $targetType dsmc
wmake $targetType coalCombustion

molecularDynamics/Allwmake $*

# ----------------------------------------------------------------- end-of-file
