/* src/lam-ssi-rpi-gm-config.h.  Generated by configure.  */
/* src/lam-ssi-rpi-gm-config.h.in.  Generated from configure.ac by autoheader.  */

/* -*- c -*-
 *
 * Copyright (c) 2001-2003 The Trustees of Indiana University.
 *                         All rights reserved.
 * Copyright (c) 1998-2001 University of Notre Dame.
 *                         All rights reserved.
 * Copyright (c) 1994-1998 The Ohio State University.
 *                         All rights reserved.
 *
 * This file is part of the LAM/MPI software package.  For license
 * information, see the LICENSE file in the top level directory of the
 * LAM/MPI source distribution.
 *
 * LAM/MPI configuation header file.
 * SSI rpi: gm module
 */

#ifndef LAM_SSI_RPI_GM_CONFIG_H
#define LAM_SSI_RPI_GM_CONFIG_H


/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <gm.h> header file. */
/* #undef HAVE_GM_H */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the `gm' library (-lgm). */
/* #undef HAVE_LIBGM */

/* Define to 1 if you have the <memory.h> header file. */
/* #undef HAVE_MEMORY_H */

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
/* #undef HAVE_STDLIB_H */

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
/* #undef HAVE_STRING_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* LAM underlying C compiler */
#define LAM_CC "gcc"

/* LAM underlying C++ compiler */
#define LAM_CXX "g++"

/* Whether we have nothrow::new or not */
#define LAM_CXX_NOTHROW_NEW 1

/* Whether nothrow::new requires an argument or not */
#define LAM_CXX_NOTHROW_NEW_ARG (std::nothrow)

/* Whether or not we have compiled with C++ exceptions support */
#define LAM_HAVE_CPP_EXCEPTION_SUPPORT 0

/* Alpha LAM SSI rpi gm version */
#define LAM_SSI_RPI_GM_ALPHA_VERSION 0

/* Version of the GM API to use */
/* #undef LAM_SSI_RPI_GM_API_VERSION */

/* Beta LAM SSI rpi gm version */
#define LAM_SSI_RPI_GM_BETA_VERSION 0

/* CVS LAM SSI rpi gm version */
#define LAM_SSI_RPI_GM_CVS_VERSION 

/* Whether the gm rpi is the default rpi or not */
#define LAM_SSI_RPI_GM_DEFAULT 0

/* Whether we have get_put() or not */
/* #undef LAM_SSI_RPI_GM_HAVE_RDMA_GET */

/* Whether we have gm_put() or gm_directed_send_with_callback() */
/* #undef LAM_SSI_RPI_GM_HAVE_RDMA_PUT */

/* Major LAM SSI rpi gm version */
#define LAM_SSI_RPI_GM_MAJOR_VERSION 1

/* Minor LAM SSI rpi gm version */
#define LAM_SSI_RPI_GM_MINOR_VERSION 2

/* Release LAM SSI rpi gm version */
#define LAM_SSI_RPI_GM_RELEASE_VERSION 0

/* Overall LAM SSI rpi gm version number */
#define LAM_SSI_RPI_GM_VERSION "1.2"

/* Whether we want checkpoing support or not not */
/* #undef LAM_SSI_RPI_GM_WANT_CHECKPOINT */

/* LAM debug flag */
#define LAM_WANT_DEBUG 0

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
/* #undef STDC_HEADERS */

/* Define to 1 if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* # undef _ALL_SOURCE */
#endif

#endif /* _LAM_SSI_RPI_GM_CONFIG_H */
