#!/bin/sh

MICORC=/dev/null
export MICORC

OPT="-ORBCSIv2"

# run Server
rm -f hello.ref
./server $OPT -ORBCSIv2Realm '@objectsecurity.com' -ORBGSSServerUser karel,cobalt &
server_pid=$!

trap "kill $server_pid > /dev/null 2> /dev/null" 0
for i in 0 1 2 3 4 5 6 7 8 9 ; do if test -r hello.ref ; then break ; else sleep 1 ; fi ; done

# run client
./client $OPT -ORBCSSNoAttr -ORBGSSClientUser karel,cobalt

