#!/bin/sh

MICORC=/dev/null
export MICORC

# run Server
PARAMS="-ORBGIOPVersion 1.2 -ORBIIOPVersion 1.2"
rm -f test.ref
./server $PARAMS &
server_pid=$!

trap "kill $server_pid > /dev/null 2> /dev/null" 0
for i in 0 1 2 3 4 5 6 7 8 9 ; do if test -r test.ref ; then break ; else sleep 1 ; fi ; done

# run client
./client $PARAMS

