
#ifndef _SECURITY_LEVEL_1_IDL_
#define _SECURITY_LEVEL_1_IDL_

#include <mico/security/security.idl>
#include <mico/current.idl>

#pragma prefix "omg.org"

module SecurityLevel1 {
    interface Current : CORBA::Current {
	Security::AttributeList get_attributes(in Security::AttributeTypeList attributes);
	Security::AttributeList get_target_attributes(in Security::AttributeTypeList attributes,
						      in Object obj);
    };
};

#endif // _SECURITY_LEVEL_1_IDL_
