#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $targetType twoPhaseMixture
wmake $targetType interfaceProperties
wmake $targetType twoPhaseProperties
wmake $targetType incompressible
wmake $targetType compressible
wmake $targetType immiscibleIncompressibleTwoPhaseMixture

# ----------------------------------------------------------------- end-of-file
