#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

# get SCOTCH_VERSION, SCOTCH_ARCH_PATH
if settings=`$WM_PROJECT_DIR/bin/foamEtcFile config/scotch.sh`
then
    . $settings
    echo "using SCOTCH_ARCH_PATH=$SCOTCH_ARCH_PATH"
else
    echo
    echo "Error: no config/scotch.sh settings"
    echo
fi


#
# define how to create an mpi-versioned library of $targetType
# compile into qualified directory
# use sentinel file to handle version changes
#
wmakeMpiLib()
{
    set +x
    for libName
    do
    (
        WM_OPTIONS="$WM_OPTIONS$WM_MPLIB"
        whichmpi="$libName/Make/$WM_OPTIONS/using:$FOAM_MPI"
        whichscotch="$libName/Make/$WM_OPTIONS/using:$SCOTCH_VERSION"
        [ -e "$whichmpi" -a -e "$whichscotch" ] || wclean $libName
        echo "wmake $targetType $libName"
        wmake $targetType $libName
        touch "$whichmpi" "$whichscotch"
    )
    done
    set -x
}

set -x

wmakeLnInclude decompositionMethods

if [ -n "$SCOTCH_ARCH_PATH" ]
then
    wmake $targetType scotchDecomp

    if [ -d "$FOAM_LIBBIN/$FOAM_MPI" ]
    then
        #- Bit of a hack: ptscotch 6 requires scotch linked as well as. Can be
        #  removed once ptscotch declares dependency on scotch itself.
        case "$SCOTCH_VERSION" in
        scotch_6.*)
            export LINK_FLAGS="-lscotch"
            ;;
        esac


        wmakeMpiLib ptscotchDecomp
    fi
else
    echo
    echo "Skipping scotchDecomp (ptscotchDecomp)"
    echo
fi


# Try and build metisDecomp (has own logic)
(cd metisDecomp && ./Allwmake $targetType)


wmake $targetType decompositionMethods

wmake $targetType decompose

# ----------------------------------------------------------------- end-of-file
