/*
 *  Demo of COSS Relationship Service
 *  Copyright (C) 1998 Karel Gardas
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 *  Send comments and/or bug reports to:
 *                 mico@informatik.uni-frankfurt.de
 *  or to my private e-mail:
 *                 gardask@alpha.inf.upol.cz
 */


#ifndef __Documents_idl__
#define __Documents_idl__


module Documents {

  interface AbstractDocument { 
    attribute string name;
    attribute string file;
    void destroy ();
  };


  interface Figure : AbstractDocument  {
  };


  interface Text : AbstractDocument  {
  };


  interface FigureFactory  {
    Figure create (in string name);
    Figure create_with_file (in string name, in string file);
  };


  interface TextFactory  {
    Text create (in string name);
    Text create_with_file (in string name, in string file);
  };

};
  
#endif


