#!/bin/sh

if [ ! "$MICODIR" ]; then
  echo
  echo "You must first set MICODIR environment variable"
  echo
  exit 1
fi

./daemons-start
./servers-start
./test
./stop-servers
./daemons-stop
rm -f ir-db.idl
rm -f ird.pid

