#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake ${1:-libo} postCalc
wmake $targetType foamCalcFunctions

functionObjects/Allwmake $*

# ----------------------------------------------------------------- end-of-file
