.TH LAM_RTRSWEEP 2 "July, 2007" "LAM 7.1.4" "LAM REMOTE LIBRARY"
.SH NAME
lam_rtrsweep, lam_rtrudie, lam_rtrwipe \- Remove LAM trace data.
.SH SYNOPSIS
.nf
int lam_rtrsweep (int node, int list);
int lam_rtrudie (int node, pid);
int lam_rtrwipe (int node);
.fi
.SH DESCRIPTION
The client functions,
.IR lam_rtrsweep() ,
.I lam_rtrudie() ,
and
.I lam_rtrwipe()
all remove trace data from the trace daemon on the given node.
The functions only differ in scope.
.I lam_rtrsweep()
removes all trace data in a given list.
If the list number is -1, all lists are selected, making the
function equivalent to
.IR lam_rtrwipe() ,
which removes all traces from the specified node.
.I lam_rtrudie()
removes all trace data marked with the given process identifier
from all lists.
If the process identifier is -1, all processes are selected, again
making the function equivalent to
.IR lam_rtrwipe() .
.SH SEE ALSO
lam_rtrget(2), lam_rtrstore(2)
