.TH LAM_RFRMFD 2 "July, 2007" "LAM 7.1.4" "LAM REMOTE LIBRARY"
.SH NAME
rfrmfd \- Control LAM specific file daemon services.
.SH SYNOPSIS
.nf
#include <freq.h>

int rfrmfd(int node, int fd);
int rfincr(int fd, int amount);
.fi
.SH DESCRIPTION
The remote function
.I rfincr()
increments the open count by
.I amount
on the file descriptor,
.IR fd .
This is necessary before a descriptor can be passed to one or
more other clients without an associated call to lam_rfopen(2).
It is used by loadgo(1) and mpirun(1) and generally not used by
application programs.
.PP
The remote function
.I rfrmfd()
sweeps clean and removes one or all of the daemon's open file
descriptors.
The target daemon is located by
.I node
and
.I fd
indicates the file descriptor handle to be removed.
If
.I fd
is NOTFD, then all open descriptors, except the standard 0, 1 and 2
are removed.
.SH SEE ALSO
lam_rfposix(2)
