.TH LAMF_RFREAD 2 "July, 2007" "LAM 7.1.4" "LAM REMOTE LIBRARY"
.SH NAME
lamf_rfread, lamf_rfwrite \- Read/write data from/to a remote file. (LAM)
.SH SYNOPSIS
.nf
subroutine lamf_rfread (udesc, buffer, inbytes, outbytes, ierror)
subroutine lamf_rfread (udesc, buffer, inbytes, outbytes, ierror)
<type> buffer(*)
integer udesc, inbytes, outbytes, ierror
.fi
.SH DESCRIPTION
These functions provide access to underlying POSIX functions, read(2)
and write(2), on any LAM node.
See lam_rfposix(2).
.PP
The length of the caller's buffer is given in the
.I inbytes
argument.
The actual number of bytes transferred is returned in the
.I outbytes
argument.
.SH SEE ALSO
lamf_rfopen(2), lamf_rfclose(2)
