.TH LAMF_RFOPEN 2 "July, 2007" "LAM 7.1.4" "LAM REMOTE LIBRARY"
.SH NAME
lamf_rfopen, lamf_rfclose \- Open or close a remote file. (LAM)
.SH SYNOPSIS
.nf
subroutine lamf_rfopen (udesc, filename, flags, mode, ierror)
character filename*(*)
integer udesc, flags, mode, ierror

subroutine lamf_rfclose (udesc, ierror)
integer udesc, ierror
.fi
.SH DESCRIPTION
These functions provide access to underlying POSIX functions, open(2)
and close(2), on any LAM node.
See lam_rfposix(2).
.PP
For convenience, the common POSIX open flags and additional LAM open
flags are defined in <FREQ.h>.
See CONSTANTS(5) for the precise values.
The flags can be added together.
.TP 18
LAM_O_RDONLY
Open for reading only.
.TP
LAM_O_WRONLY
Open for writing only.
.TP
LAM_O_RDWR
Open for reading and writing.
.TP
LAM_O_APPEND
Append on each write.
.TP
LAM_O_CREAT
Create the file if it does not exist.
.TP
LAM_O_TRUNC
Truncate the file length to 0.
.TP
LAM_O_EXCL
Report an error if trying to create an existing file.
.TP
LAM_O_REUSE
Reuse existing file descriptor opened with same file name, if possible.
.SH SEE ALSO
lamf_rfread(2), lamf_rfwrite(2)
