.TH RECHO 2 "July, 2007" "LAM 7.1.4" "LAM REMOTE LIBRARY"
.SH NAME
recho \- Send messages to LAM echo server.
.SH SYNOPSIS
.HP
int recho (int node, char *src_msg, char *dest_msg, int length);
.SH ARGUMENTS
.TP 12
node
location of echo service
.TP
src_msg
outgoing message
.TP
dest_msg
incoming echo message
.TP
length
of both message buffers
.SH DESCRIPTION
The echo server returns any message that it receives to the sender.
It is a confidence testing service for the LAM network.
.PP
The message
.I length
must not exceed the maximum network message length MAXNMSGLEN, defined in
<net.h> and factory set to 8192 bytes.
.SH RETURN VALUE
Upon successful completion, the number of bytes echoed is returned.
If an error occurred, \-1 is returned and the global variable
.I errno
is set to indicate the error.
.SH ERRORS
.TP 16
EMSGLEN
The message length exceeds the maximum message length.
.SH SEE ALSO
tping(1)
