.TH TRROR 2 "July, 2007" "LAM 7.1.4" "LAM FORTRAN LIBRARY"
.SH NAME
TRROR \- Print LAM system error message.
.SH SYNOPSIS
subroutine TRROR (strname)
.br
character strname*(*)
.SH DESCRIPTION
The most recent error message is displayed.
Many LAM subroutines have an
.I ierror
argument that returns an error code.
If
.I TRROR()
is invoked immediately after detecting an error condition from
a LAM subroutine, the description corresponding to the
.I ierror
code will be displayed.
The error message will be preceded by the contents of
.IR strname .
.SH EXAMPLE
.RS
.nf
call KENTR('app', 0, ierror)
if (ierror .ne. 0) call TRROR('knit')
.fi
.RE
