#!/bin/sh
set -x

if [ "$WM_CC" ]      ; then export CC="$WM_CC"; fi
if [ "$WM_CXX" ]     ; then export CXX="$WM_CXX"; fi
if [ "$WM_CFLAGS" ]  ; then export CFLAGS="$WM_CFLAGS"; fi
if [ "$WM_CXXFLAGS" ]; then export CXXFLAGS="$WM_CXXFLAGS"; fi
if [ "$WM_LDFLAGS" ]  ; then export LDFLAGS="$WM_LDFLAGS"; fi

wmake libso zlib-1.2.1

if [ "$WM_MPLIB" = "OPENMPI" -a ! -r $OPENMPI_ARCH_PATH/lib/libmpi.a -a ! -r $OPENMPI_ARCH_PATH/lib/libmpi.so ]
then
(
    cd $OPENMPI_HOME

    make distclean
    rm -rf $OPENMPI_ARCH_PATH

    ./configure \
        --prefix=$OPENMPI_ARCH_PATH \
        --disable-mpirun-prefix-by-default \
        --disable-orterun-prefix-by-default \
        --enable-shared --disable-static \
        --disable-mpi-f77 --disable-mpi-f90 --disable-mpi-cxx \
        --disable-mpi-profile
        # These lines enable Infiniband support
        # --with-openib=/usr/local/ofed \
        # --with-openib-libdir=/usr/local/ofed/lib64

    make
    make install
    make distclean
)
fi

if [ "$WM_MPLIB" = "LAM" -a ! -r $LAM_ARCH_PATH/lib/libmpi.a -a ! -r $LAM_ARCH_PATH/lib/libmpi.so ]
then
(
    cd $LAMHOME

    make distclean
    rm -rf $LAM_ARCH_PATH

    ./configure \
        --prefix=$LAM_ARCH_PATH \
        --enable-shared \
        --disable-static \
        --without-romio \
        --without-mpi2cpp \
        --without-profiling \
        --without-fc

    make
    make install
    make distclean
)
fi

if [ "$WM_MPLIB" = "MPICH" -a ! -r $MPICH_ARCH_PATH/lib/libmpich.a -a ! -r $MPICH_ARCH_PATH/lib/libmpich.so ]
then
(
    cd $MPICH_PATH

    make distclean
    rm -rf $MPICH_ARCH_PATH
    rm util/machines/machines.*

    ./configure \
        --without-mpe \
        --disable-f77 \
        --disable-f90 \
        --disable-f90modules \
        --disable-c++ \
        --disable-mpedbg \
        --disable-devdebug \
        --disable-debug \
        --enable-sharedlib=$MPICH_ARCH_PATH/lib \
        --with-device=ch_p4 \
        -prefix=$MPICH_ARCH_PATH
    make
    make install
    make distclean

    if [ -r $MPICH_ARCH_PATH ]
    then
    (
        cd $MPICH_ARCH_PATH/bin
        for file in *
        do
            sed s%$MPICH_ARCH_PATH%'$MPICH_ARCH_PATH'%g $file > temp.$$
            mv temp.$$ $file
            chmod ugo+rx $file
        done

        cd $MPICH_ARCH_PATH/lib

        if [ -r libmpich.so.1.0 ]
        then
            rm *.so
            ln -s libmpich.so.1.0 libmpich.so
        fi
    )
    fi
)
fi


( cd malloc && ./Allwmake )


if [ "$MICO_ARCH_PATH" -a ! -r $MICO_ARCH_PATH/lib/libmico${MICO_VERSION}.a ]
then
(
    cd $MICO_PATH
    make distclean
    ./configure --prefix=$MICO_ARCH_PATH --disable-shared --without-x
    make
    make install
    make distclean
)
fi

# ----------------------------------------------------------------- end-of-file
