#!/bin/sh

ADDR=ssl:inet:`uname -n`:12456

# run Server
./server -ORBIIOPAddr $ADDR -ORBSSLcert ServerCert.pem -ORBSSLkey ServerKey.pem -ORBSSLverify 0&
server_pid=$!
sleep 1

trap "kill $server_pid" 0

# run client
./client -ORBBindAddr $ADDR -ORBSSLcert ClientCert.pem -ORBSSLkey ClientKey.pem -ORBSSLverify 0

