#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean

wclean sprayDyMFoam
wclean sprayEngineFoam

# ----------------------------------------------------------------- end-of-file
