#!/bin/sh
PATH=../../daemon:../../coss/naming:../../imr:../../ir:$PATH
ADDR=inet:`uname -n`:12456
IRADDR=inet:`uname -n`:12500
DOCUMENT=inet:`uname -n`:13002
REFERENCE=inet:`uname -n`:13300
CONTAINMENT=inet:`uname -n`:13400
NODE=inet:`uname -n`:13500
TEST=inet:`uname -n`:13600
TRAVERSAL=inet:`uname -n`:13700
CRITERIA=inet:`uname -n`:13800
FACTORY=inet:`uname -n`:13900
TRADER=inet:`uname -n`:14000
OPERATION=inet:`uname -n`:14100
RANDOMD=inet:`uname -n`:15000

sleep 10
CMD="./simple-test -ORBBindAddr $CONTAINMENT -ORBBindAddr $REFERENCE -ORBBindAddr $NODE -ORBBindAddr $DOCUMENT -ORBIfaceRepoAddr $IRADDR -ORBBindAddr $TEST -ORBBindAddr $TRAVERSAL -ORBBindAddr $CRITERIA -ORBBindAddr $FACTORY -ORBBindAddr $OPERATION"
#echo $CMD
eval $CMD
#gdb ./simple-test

