#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.pre

#runApplication `getApplication`
runParallel `getApplication` 5
runApplication reconstructParMesh -latestTime
runApplication reconstructPar -latestTime


# ----------------------------------------------------------------- end-of-file
