.TH FCTL 1 "July, 2007" "LAM 7.1.4" "LAM COMMANDS"
.SH NAME
fctl \- Control a LAM remote file daemon.
.SH SYNOPSIS
fctl [-hS] [-s descno] nodes [newdir]
.SH OPTIONS
.TP 14
.B \-h
Print the command help menu.
.TP
.B \-S
Sweep out all but the standard filed descriptors.
.TP
.B \-s descno
Sweep out the given filed descriptor.
.TP
.B nodes
Direct command to filed on these nodes.
.TP
.B newdir
Change to new working directory.
.SH DESCRIPTION
Most MPI users will probably not need to use the
.I fctl
command; see lamclean(1).  This command is only installed if LAM/MPI
was configured with the
.I --with-trillium
switch.
.PP
The
.I fctl
command controls important file daemon (filed) attributes and support features.
With no options,
.I fctl
reports the current working directory that is prepended to all partial
pathnames on rfopen(2).
A file name on the command line becomes the new working directory.
.PP
Another important role of
.I fctl
is cleaning the debris that can form in filed in certain application
crashes or bugs.
Any file descriptor can be swept clean by indicating its handle (number)
with the
.I \-c
option.
If desired, all descriptors, save stdio (0, 1, 2), can be cleaned
and filed effectively reset with the
.I \-S
option.
.SH EXAMPLE
.TP 4
fctl h data/set1
Change current working directory as indicated.
.TP
fctl h -s 4
Close and remove filed descriptor 4.
.SH SEE ALSO
fstate(1),
lamclean(1)
