.TH HCC 1 "July, 2007" "LAM 7.1.4" "LAM TOOLS"
.SH NAME
mpicc, mpiCC, hcc, hcp \- Compile LAM/MPI C/C++ programs.
.SH SYNOPSIS
hcc [-showme] ...
.PP
hcp [-showme] ...
.SH OPTIONS
.TP
-showme
Does not invoke the underlying C/C++ compiler.  Instead, it shows the
command line that would be executed to compile the C/C++ program.
.PP
See cc(1) and CC(1) (or whatever your underlying C/C++ compilers are)
for all other options.
.SH DESCRIPTION
The names
.I hcc 
and 
.I hcp
have been deprecated in favor of
.I mpicc 
and 
.IR mpiCC .
Please see their corresponding man pages.
.SH SEE ALSO
cc(1), CC(1), ld(1), mpicc(1), mpiCC(1), mpif77(1)
