.TH HF77 1 "July, 2007" "LAM 7.1.4" "LAM TOOLS"
.SH NAME
mpif77, hf77 \- Compile LAM FORTRAN programs.
.SH SYNOPSIS
hf77
[-showme] ...
.SH DESCRIPTION
See f77(1) (or whatever your underlying FORTRAN compiler is) for all
other options.
.PP
The name
.I hf77
has been deprecated in favor of
.IR mpif77 .
Please see its corresponding man page.
.SH SEE ALSO
f77(1), ld(1), mpicc(1), mpiCC(1), mpif77(1)
