.TH LAMCHECKPOINT 1 "July, 2007" "LAM 7.1.4" "LAM TOOLS"
.SH NAME
lamcheckpoint \- Checkpoint a LAM/MPI job.
.SH SYNOPSIS
lamcheckpoint -ssi cr self|blcr -pid pidofmpirun  
.SH OPTIONS
.TP 12
.B \-h
Print the command help menu.
.SH DESCRIPTION
The
.I lamcheckpoint
tool checkpoints the LAM software on each of the nodes that were
initially booted with
.I lamboot
and/or 
.IR lamgrow .
.I lamcheckpoint 
calls the checkpoint function specific to the specified SSI module.
.PP
The arguments to 
.I lamcheckpoint
should contain the SSI parameter indicating the name of the Checkpoint module
At present, there are only two Checkpoint modules namely, 'self' and 'blcr'.  
Regardless of the Checkpoint module selected, the pid of mpirun should be given 
as an argument to   
.IR lamcheckpoint .
.SH EXAMPLES
.TP 4
lamcheckpoint -ssi cr self -pid 1024
.TP
lamcheckpoint -ssi cr blcr -pid 1024 -ssi cr_blcr_base_dir /path/to/context/file/dir
.SH SEE ALSO
lamrestart(1), recon(1), lamboot(1), tkill(1), bhost(5), lam-helpfile(5), lamwipe(1)
