.TH LAMCLEAN 1 "July, 2007" "LAM 7.1.4" "LAM COMMANDS"
.SH NAME
lamclean \- Attempt to clean entire LAM system.
.SH SYNOPSIS
lamclean [-hv]
.SH OPTIONS
.TP 8
.B \-h
Print the command help menu.
.TP
.B \-v
Be verbose.
.SH DESCRIPTION
The
.I lamclean
command attempts to remove all user processes and messages from all nodes.
It also de\-allocates all user allocated resources and cancels all
user process registrations.
This happens by invoking many different remote services which have
previously been invoked individually by several other commands.
These commands should still be used when partial selective removal
of user presence is desired.
Otherwise,
.I lamclean
is a quick and convenient way of starting over after a bad application
run without rebooting the system.
.PP
.I lamclean
takes the following actions on the following system processes on all nodes:
.PP
.TP 15
kenyad
The LAM SIGUDIE signal (terminate) is sent to all user processes.
See doom(1).
.TP
bufferd
The entire daemon is reset to its initial state after booting.
See sweep(1).
.TP
filed
All user file descriptors are closed.
See fctl(1).
.TP
traced
All traces are removed.
See lamtrace(1).
.PP
.I lamclean
will not succeed if any of the nodes are unreachable due to catastrophic
failure or maximum buffer overflow with link jamming.
If
.I lamclean
does not return, use lamwipe(1) and lamboot(1) to restart the
multicomputer.
.SH SEE ALSO
lamboot(1), lamwipe(1), sweep(1), doom(1), fctl(1), lamtrace(1)
