.TH LAM 1 "July, 2007" "LAM 7.1.4" "LAM OVERVIEW"
.SH NAME
LAM \- introduction to Local Area Multicomputer (LAM)
.SH DESCRIPTION
LAM is an MPI programming environment and development system for a
message-passing parallel machine constituted with heterogeneous UNIX
computers on a network.  With LAM, a dedicated cluster or an existing
network computing infrastructure can act as one parallel computer
solving one compute-intensive problem.  LAM emphasizes productivity in
the application development cycle with extensive control and
monitoring functionality.  The user can easily debug the common errors
in parallel programming and is well equipped to diagnose more
difficult problems.
.PP
LAM features a full implementation of the MPI communication standard,
with the exception that the MPI_CANCEL function will not properly
cancel messages that have been sent.
.PP
.SS User Information
Users are strongly encouraged to read the
.I LAM/MPI User's Guide
that is included with the LAM/MPI distribution, and is provided on the
main LAM/MPI web site
.RI ( http://www.lam-mpi.org/ ).
.SS Up-to-Date Information
The LAM home page can be found on the World Wide Web at:
.IR http://www.lam-mpi.org/ .
It should be consulted for the most current information about LAM, as
well as updates, patches, etc.
.SH SEE ALSO
.SS Overview of Commands and Libraries
introu(1), introc(2), INTROF(2)
.SS System Services Interface (SSI)
lamssi(7), lamssi_boot(7), lamssi_coll(7), lamssi_rpi(7)
.SS Starting / Stopping LAM
recon(1), lamboot(1), lamhalt(1), lamnodes(1), lamwipe(1),
tping(1), lamgrow(1), lamshrink(1)
.SS Compiling MPI Applications
mpicc(1), mpiCC(1), mpif77(1)
.SS Running MPI Applications
mpirun(1), lamclean(1)
.SS Running Non-MPI Applications
lamexec(1)
.SS Monitoring MPI Applications
mpitask(1)
.SS Unloading MPI Trace Data
lamtrace(1)
.SS Reference Documents
.TP
"LAM/MPI Installation Guide"
included in the LAM/MPI distribution and available on
.I http://www.lam-mpi.org/
.TP
"LAM/MPI User's Guide"
included in the LAM/MPI distribution and available on
.I http://www.lam-mpi.org/
.TP
"LAM Frequently Asked Questions"
at
.I http://www.lam-mpi.org/faq/
.TP
"MPI Primer / Developing with LAM", Ohio Supercomputer Center
.TP
"MPI: A Message-Passing Interface Standard", Message-Passing Interface Forum, version 1.1
at 
.I http://www.mpi-forum.org/
.TP
"MPI-2: Extensions to the Message Passing Interface", Message Passing Interface Forum, version 2.0
at
.I http://www.mpi-forum.org/
.SS MPI Quick Tutorials
.TP
"LAM/MPI ND User Guide / Introduction"
at
.I http://www.lam-mpi.org/mpi/tutorials/lam/
.TP
"MPI: It's Easy to Get Started"
.TP
"MPI: Everyday Datatypes"
.TP
"MPI: Everyday Collective Communication"
.SS Guaranteed Envelope Resources
.HP
"Robust MPI Message Delivery Through Guaranteed Resources",
MPI Developer's Conference, 1995
