#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $targetType scotchDecomp
wmake $targetType ptscotchDecomp
wmake $targetType metisDecomp
wmake $targetType MGridGen


# ----------------------------------------------------------------- end-of-file
